# Generated by Django 2.1.1 on 2019-04-15 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_column='source_id', verbose_name='资源id')),
                ('user', models.CharField(max_length=100, verbose_name='使用者用户名')),
                ('use_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='使用时间')),
                ('source_value', models.IntegerField(default=80, verbose_name='资源价值')),
            ],
            options={
                'verbose_name': '已被使用资源',
                'verbose_name_plural': '已被使用资源',
                'db_table': 'buys_list',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_sourcename', models.CharField(max_length=100, verbose_name='评论资源用户名')),
                ('comment_name', models.CharField(max_length=100, verbose_name='评论用户名')),
                ('source_id', models.IntegerField(db_column='sourceid', default=1, verbose_name='评论资源id')),
                ('comment_content', models.TextField(default='？？', verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'Comment_list',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_name', models.CharField(max_length=100, verbose_name='发消息用户名')),
                ('receive_name', models.CharField(max_length=100, verbose_name='接收者用户名')),
                ('info_content', models.TextField(default='？？', verbose_name='消息内容')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('read_sure', models.BooleanField(default=False, verbose_name='是否已经被阅读')),
            ],
            options={
                'verbose_name': '消息表',
                'verbose_name_plural': '消息表',
                'db_table': 'Info_list',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='资源介绍')),
                ('source_picurl', models.CharField(max_length=100, verbose_name='资源图片展示地址')),
                ('source_bgurl', models.CharField(max_length=300, verbose_name='资源网盘或开源连接')),
                ('source_psw', models.CharField(default='', max_length=150, verbose_name='资源网盘密码')),
                ('source_valuemarks', models.IntegerField(default=50, verbose_name='资源值B币数')),
                ('source_type', models.CharField(max_length=150, verbose_name='资源类型')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分享时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='浏览量')),
                ('load_nums', models.IntegerField(default=0, verbose_name='使用量')),
                ('share_name', models.CharField(max_length=100, verbose_name='分享资源用户名')),
                ('source_price', models.IntegerField(default=80, verbose_name='市场价值')),
            ],
            options={
                'verbose_name': '我的资源',
                'verbose_name_plural': '我的资源',
                'db_table': 'Posts_list',
            },
        ),
    ]
