# Generated by Django 2.1.1 on 2019-05-18 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('black', '0002_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100, verbose_name='提问者用户名')),
                ('question_content', models.TextField(default='？？', verbose_name='提问内容')),
                ('question_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提问时间')),
            ],
            options={
                'verbose_name': '提问表',
                'verbose_name_plural': '提问表',
                'db_table': 'question_list',
            },
        ),
        migrations.AlterField(
            model_name='img',
            name='img_name',
            field=models.CharField(default='1', max_length=20, verbose_name='图片名'),
        ),
    ]
