# Generated by Django 2.1.1 on 2019-04-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_list',
            new_name='Ulist',
        ),
    ]
