# Generated by Django 2.1.1 on 2019-05-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190415_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_headpicurl',
            field=models.CharField(default='', max_length=100, verbose_name='用户头像地址'),
        ),
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='个人说明'),
        ),
    ]
